import { DataSource } from 'typeorm';
import { config } from 'dotenv';
import * as path from 'path';
import * as fs from 'fs';
import * as bcrypt from 'bcrypt';
import { randomUUID } from 'crypto';

// Charger les variables d'environnement
const envFile = `.env.${process.env.NODE_ENV || 'development'}`;
const envPath = path.join(__dirname, '../../../', envFile);

if (fs.existsSync(envPath)) {
  config({ path: envPath });
}

const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432'),
  username: process.env.DB_USERNAME || 'postgres',
  password: process.env.DB_PASSWORD || 'postgres',
  database: process.env.DB_DATABASE || 'hgpd_dev',
  synchronize: false,
  logging: false,
});

// Données de prestataires à ajouter (80 total)
const PROVIDERS_DATA_ADDITIONAL = [
  // Lieux d'événements (10)
  {
    firstName: 'Demba',
    lastName: 'Diallo',
    companyName: 'Centre Culturel Dakar Premium',
    activity: 'Salle de conférence',
    phone: '+221771300001',
    email: 'demba.diallo@centreculturel.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Salle polyvalente avec audiovisuel',
    categoryId: 190,
  },
  {
    firstName: 'Aya',
    lastName: 'Ba',
    companyName: 'Villa Royale Luxury',
    activity: 'Location de villa haut standing',
    phone: '+221771300002',
    email: 'aya.ba@villaroyale.sn',
    department: 'Thiès',
    commune: 'Mbour',
    shortDescription: 'Villa moderne avec piscine et jardin',
    categoryId: 190,
  },
  {
    firstName: 'Sidi',
    lastName: 'Gueye',
    companyName: 'Auberge Océan Bleu',
    activity: 'Auberge',
    phone: '+221771300003',
    email: 'sidi.gueye@auberge.sn',
    department: 'Saint-Louis',
    commune: 'Saint-Louis',
    shortDescription: 'Auberge de charme avec vue fleuve',
    categoryId: 190,
  },
  {
    firstName: 'Ndeye',
    lastName: 'Sow',
    companyName: 'Plage Loisirs Event',
    activity: 'Espace plage',
    phone: '+221771300004',
    email: 'ndeye.sow@plageevent.sn',
    department: 'Kaolack',
    commune: 'Kaolack',
    shortDescription: 'Espace plage privatisable',
    categoryId: 190,
  },
  {
    firstName: 'Lamine',
    lastName: 'Sall',
    companyName: 'Golf Resort Senegal',
    activity: 'Resort événementiel',
    phone: '+221771300005',
    email: 'lamine.sall@golfresort.sn',
    department: 'Thiès',
    commune: 'Saly',
    shortDescription: 'Resort avec terrain de golf',
    categoryId: 190,
  },
  {
    firstName: 'Aïssatou',
    lastName: 'Faye',
    companyName: 'Boutique Hôtel Prestige',
    activity: 'Hôtel boutique',
    phone: '+221771300006',
    email: 'aissatou.faye@boutique.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Petit hôtel de charme 4 étoiles',
    categoryId: 190,
  },
  {
    firstName: 'Cheikh',
    lastName: 'Ndiaye',
    companyName: 'Palais du Roi Événements',
    activity: 'Grand palais',
    phone: '+221771300007',
    email: 'cheikh.ndiaye@palais.sn',
    department: 'Dakar',
    commune: 'Guédiawaye',
    shortDescription: 'Grand palais pouvant accueillir 1000 personnes',
    categoryId: 190,
  },
  {
    firstName: 'Fatou',
    lastName: 'Sarr',
    companyName: 'Riad Maroc Sens',
    activity: 'Riad traditionnel',
    phone: '+221771300008',
    email: 'fatou.sarr@riad.sn',
    department: 'Dakar',
    commune: 'Médina',
    shortDescription: 'Riad traditionnel avec patio central',
    categoryId: 190,
  },
  {
    firstName: 'Mamadou',
    lastName: 'Diop',
    companyName: 'Bistro Belle Vue',
    activity: 'Restaurant boutique',
    phone: '+221771300009',
    email: 'mamadou.diop@bistro.sn',
    department: 'Thiès',
    commune: 'Mbour',
    shortDescription: 'Petit restaurant avec vue panoramique',
    categoryId: 190,
  },
  {
    firstName: 'Safiatou',
    lastName: 'Gueye',
    companyName: 'Beach Club Paradise',
    activity: 'Beach club',
    phone: '+221771300010',
    email: 'safiatou.gueye@beach.sn',
    department: 'Kaolack',
    commune: 'Kaolack',
    shortDescription: 'Beach club avec cabanas',
    categoryId: 190,
  },

  // Matériel (10)
  {
    firstName: 'Ousmane',
    lastName: 'Sow',
    companyName: 'Éclairage LED Pro',
    activity: 'Éclairage événementiel',
    phone: '+221771300011',
    email: 'ousmane.sow@eclairage.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Éclairage LED haute puissance',
    categoryId: 191,
  },
  {
    firstName: 'Mariama',
    lastName: 'Ba',
    companyName: 'Studio Photo Pro',
    activity: 'Photographe professionnel',
    phone: '+221771300012',
    email: 'mariama.ba@studiopl.sn',
    department: 'Dakar',
    commune: 'Plateau',
    shortDescription: 'Studio photos avec équipement haut de gamme',
    categoryId: 191,
  },
  {
    firstName: 'Ibrahima',
    lastName: 'Gueye',
    companyName: 'Video Production House',
    activity: 'Production vidéo',
    phone: '+221771300013',
    email: 'ibrahima.gueye@videopro.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Production vidéo 4K et drone',
    categoryId: 191,
  },
  {
    firstName: 'Halimatou',
    lastName: 'Diop',
    companyName: 'Location Chaises Premium',
    activity: 'Location de mobilier',
    phone: '+221771300014',
    email: 'halimatou.diop@chairs.sn',
    department: 'Thiès',
    commune: 'Mbour',
    shortDescription: 'Chaises Chiavari, tables décorées',
    categoryId: 191,
  },
  {
    firstName: 'Pape',
    lastName: 'Sarr',
    companyName: 'Tonnelles Events',
    activity: 'Location de tonnelles',
    phone: '+221771300015',
    email: 'pape.sarr@tonnelles.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Tonnelles et bâches de qualité',
    categoryId: 191,
  },
  {
    firstName: 'Ndeye',
    lastName: 'Ndiaye',
    companyName: 'Studio Son Professionnel',
    activity: 'Sonorisation',
    phone: '+221771300016',
    email: 'ndeye.ndiaye@studio.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Système de son complet avec DJ booth',
    categoryId: 191,
  },
  {
    firstName: 'Modou',
    lastName: 'Ba',
    companyName: 'Drones et Aériens',
    activity: 'Prise de vue par drone',
    phone: '+221771300017',
    email: 'modou.ba@drones.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Drone 4K et photographies aériennes',
    categoryId: 191,
  },
  {
    firstName: 'Aissatou',
    lastName: 'Sall',
    companyName: 'Montage Expo Events',
    activity: 'Montage scénographie',
    phone: '+221771300018',
    email: 'aissatou.sall@montage.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: "Montage et démontage d'événements",
    categoryId: 191,
  },
  {
    firstName: 'Yacine',
    lastName: 'Gueye',
    companyName: 'Générateurs Premium',
    activity: 'Location groupes électrogènes',
    phone: '+221771300019',
    email: 'yacine.gueye@generateurs.sn',
    department: 'Thiès',
    commune: 'Mbour',
    shortDescription: 'Générateurs silencieux pour événements',
    categoryId: 191,
  },
  {
    firstName: 'Fatima',
    lastName: 'Diallo',
    companyName: 'Écrans Géants Video',
    activity: 'Location écrans LED',
    phone: '+221771300020',
    email: 'fatima.diallo@ecrans.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Écrans LED géants pour événements',
    categoryId: 191,
  },

  // Traiteur (12)
  {
    firstName: 'Khadim',
    lastName: 'Ba',
    companyName: 'Cuisine Yor Traditionnel',
    activity: 'Traiteur cuisine sénégalaise',
    phone: '+221771300021',
    email: 'khadim.ba@cuisineyor.sn',
    department: 'Kaolack',
    commune: 'Kaolack',
    shortDescription: 'Spécialiste thiéboudienne et riz gras',
    categoryId: 192,
  },
  {
    firstName: 'Coumba',
    lastName: 'Sow',
    companyName: 'Spécial Mafé & Cie',
    activity: 'Mafé et plats traditionnels',
    phone: '+221771300022',
    email: 'coumba.sow@mafe.sn',
    department: 'Kaolack',
    commune: 'Kaolack',
    shortDescription: 'Mafé, yassa, domoda authentiques',
    categoryId: 192,
  },
  {
    firstName: 'Aïda',
    lastName: 'Gueye',
    companyName: 'La Cuisine Italienne Raffinée',
    activity: 'Cuisine italienne',
    phone: '+221771300023',
    email: 'aida.gueye@italian.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Pâtes fraîches et pizzas tradition',
    categoryId: 192,
  },
  {
    firstName: 'Samba',
    lastName: 'Ndiaye',
    companyName: 'Gourmet Asiatique Prestige',
    activity: 'Cuisine asiatique',
    phone: '+221771300024',
    email: 'samba.ndiaye@asiatique.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Cuisine thaï, chinoise et vietnamienne',
    categoryId: 192,
  },
  {
    firstName: 'Awa',
    lastName: 'Diop',
    companyName: 'Pâtisserie Gourmande',
    activity: 'Pâtisserie fine',
    phone: '+221771300025',
    email: 'awa.diop@patisserie.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Gâteaux personnalisés et pièces montées',
    categoryId: 192,
  },
  {
    firstName: 'Thierno',
    lastName: 'Ba',
    companyName: 'Cocktail Bar Premium',
    activity: 'Apéro et cocktails',
    phone: '+221771300026',
    email: 'thierno.ba@cocktail.sn',
    department: 'Dakar',
    commune: 'Plateau',
    shortDescription: 'Bar à cocktails avec barman professionnel',
    categoryId: 192,
  },
  {
    firstName: 'Miriam',
    lastName: 'Sarr',
    companyName: 'Catering Prestige Plus',
    activity: 'Catering complet',
    phone: '+221771300027',
    email: 'miriam.sarr@catering.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Service complet avec serveurs et cuisinier',
    categoryId: 192,
  },
  {
    firstName: 'Mactar',
    lastName: 'Gueye',
    companyName: 'BBQ Fest Senegal',
    activity: 'Barbecue et grillades',
    phone: '+221771300028',
    email: 'mactar.gueye@bbq.sn',
    department: 'Thiès',
    commune: 'Mbour',
    shortDescription: 'Grillades et barbecue tradition',
    categoryId: 192,
  },
  {
    firstName: 'Aïssatou',
    lastName: 'Ba',
    companyName: 'Pizza Mobile Delux',
    activity: 'Pizzeria mobile',
    phone: '+221771300029',
    email: 'aissatou.ba@pizzamobile.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Four à pizza mobile avec pizzaiolo',
    categoryId: 192,
  },
  {
    firstName: 'Oumy',
    lastName: 'Diallo',
    companyName: 'Crêperie Gourmande Bretonne',
    activity: 'Crêpes et galettes',
    phone: '+221771300030',
    email: 'oumy.diallo@creperie.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Crêpes bretonnes authentiques',
    categoryId: 192,
  },
  {
    firstName: 'Malick',
    lastName: 'Ndiaye',
    companyName: 'Jus Fruits Frais Artisanal',
    activity: 'Jus et boissons frais',
    phone: '+221771300031',
    email: 'malick.ndiaye@jus.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Jus frais pressés et smoothies',
    categoryId: 192,
  },
  {
    firstName: 'Ndèye',
    lastName: 'Faye',
    companyName: 'Côté Chaud Food Truck',
    activity: 'Food truck',
    phone: '+221771300032',
    email: 'ndeye.faye@foodtruck.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Food truck avec cuisine variée',
    categoryId: 192,
  },

  // Décoration (10)
  {
    firstName: 'Aminata',
    lastName: 'Gueye',
    companyName: 'Fleurs Exotiques Prestige',
    activity: 'Arrangements floraux',
    phone: '+221771300033',
    email: 'aminata.gueye@fleurs.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Arrangements floraux haut de gamme',
    categoryId: 193,
  },
  {
    firstName: 'Oumou',
    lastName: 'Ba',
    companyName: 'Design Salle Événement',
    activity: 'Design intérieur événementiel',
    phone: '+221771300034',
    email: 'oumou.ba@designsalle.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Conception et décoration de salle',
    categoryId: 193,
  },
  {
    firstName: 'Halimatou',
    lastName: 'Ba',
    companyName: 'Ballons et Décorations',
    activity: 'Ballons et guirlandes',
    phone: '+221771300035',
    email: 'halimatou.ba@ballons.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Sculptures ballons et arches',
    categoryId: 193,
  },
  {
    firstName: 'Khadi',
    lastName: 'Diallo',
    companyName: 'Nappes et Linges Premium',
    activity: 'Location de linges',
    phone: '+221771300036',
    email: 'khadi.diallo@linges.sn',
    department: 'Thiès',
    commune: 'Mbour',
    shortDescription: 'Nappes, chemins, serviettes luxe',
    categoryId: 193,
  },
  {
    firstName: 'Mariam',
    lastName: 'Gueye',
    companyName: 'Bougies Décoratives Luxe',
    activity: 'Bougies et luminaires',
    phone: '+221771300037',
    email: 'mariam.gueye@bougies.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Bougies odorantes et chandeliers',
    categoryId: 193,
  },
  {
    firstName: 'Sidy',
    lastName: 'Ba',
    companyName: 'Métallurgie Décor Art',
    activity: 'Décor métallique et arches',
    phone: '+221771300038',
    email: 'sidy.ba@metalarts.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Arches en métal et structures décor',
    categoryId: 193,
  },
  {
    firstName: 'Fatoumata',
    lastName: 'Sarr',
    companyName: 'Chaise Chiavari Prestige',
    activity: 'Location chaises décorées',
    phone: '+221771300039',
    email: 'fatoumata.sarr@chiavari.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Chaises Chiavari dorées et argentées',
    categoryId: 193,
  },
  {
    firstName: 'Ndiaye',
    lastName: 'Sow',
    companyName: 'Photobooth Créatif',
    activity: 'Photobooth avec accessoires',
    phone: '+221771300040',
    email: 'ndiaye.sow@photobooth.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Photobooth avec effets et personnalisation',
    categoryId: 193,
  },
  {
    firstName: 'Coumba',
    lastName: 'Ndiaye',
    companyName: 'Miroirs et Panneaux Déco',
    activity: 'Décoration murale',
    phone: '+221771300041',
    email: 'coumba.ndiaye@miroirs.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Miroirs dorés et panneaux personnalisés',
    categoryId: 193,
  },
  {
    firstName: 'Yacine',
    lastName: 'Diallo',
    companyName: 'Location Tables Décorées',
    activity: 'Tables cocktail et hautes',
    phone: '+221771300042',
    email: 'yacine.diallo@tables.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Tables décorées avec housses luxe',
    categoryId: 193,
  },

  // Transports (10)
  {
    firstName: 'Mamadou',
    lastName: 'Sarr',
    companyName: 'Uber Prestige Dakar',
    activity: 'VTC service premium',
    phone: '+221771300043',
    email: 'mamadou.sarr@uberprestige.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Service VTC voiture premium',
    categoryId: 194,
  },
  {
    firstName: 'Fallou',
    lastName: 'Ba',
    companyName: 'Limousine Prestige Events',
    activity: 'Limousine service',
    phone: '+221771300044',
    email: 'fallou.ba@limousine.sn',
    department: 'Dakar',
    commune: 'Plateau',
    shortDescription: 'Service limousine noir avec chauffeur',
    categoryId: 194,
  },
  {
    firstName: 'Abdoulaye',
    lastName: 'Gueye',
    companyName: 'Mercedes Classe S Prestige',
    activity: 'Location voiture prestige',
    phone: '+221771300045',
    email: 'abdoulaye.gueye@mercedes.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Mercedes de luxe avec chauffeur',
    categoryId: 194,
  },
  {
    firstName: 'Aïssatou',
    lastName: 'Diallo',
    companyName: 'Bus Climatisé Confort',
    activity: 'Location bus climatisé',
    phone: '+221771300046',
    email: 'aissatou.diallo@busconfort.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Bus climatisé 50 places avec chauffeur',
    categoryId: 194,
  },
  {
    firstName: 'Maram',
    lastName: 'Ndiaye',
    companyName: 'Minibus 14 Places',
    activity: 'Location minibus',
    phone: '+221771300047',
    email: 'maram.ndiaye@minibus.sn',
    department: 'Thiès',
    commune: 'Mbour',
    shortDescription: 'Minibus climatisé 14 places',
    categoryId: 194,
  },
  {
    firstName: 'Mamadou',
    lastName: 'Sall',
    companyName: 'Chauffeurs Privés Elite',
    activity: 'Service chauffeur privé',
    phone: '+221771300048',
    email: 'mamadou.sall@chauffeurs.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Chauffeurs anglicistes expérimentés',
    categoryId: 194,
  },
  {
    firstName: 'Ndeye',
    lastName: 'Sarr',
    companyName: 'Vespa Prestige Tours',
    activity: 'Location de scooters',
    phone: '+221771300049',
    email: 'ndeye.sarr@vespa.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Vespa et scooters pour tours',
    categoryId: 194,
  },
  {
    firstName: 'Ousmane',
    lastName: 'Diallo',
    companyName: 'Bicyclette Event Tours',
    activity: 'Location de vélos',
    phone: '+221771300050',
    email: 'ousmane.diallo@velos.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Vélos décorés pour événement',
    categoryId: 194,
  },
  {
    firstName: 'Safiatou',
    lastName: 'Ba',
    companyName: 'Taxi Blanc Service',
    activity: 'Service taxi collectif',
    phone: '+221771300051',
    email: 'safiatou.ba@taxiblanc.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Taxis blancs pour transferts',
    categoryId: 194,
  },
  {
    firstName: 'Babacar',
    lastName: 'Gueye',
    companyName: 'Bateau Privé Event Cruise',
    activity: 'Location bateau privé',
    phone: '+221771300052',
    email: 'babacar.gueye@bateau.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Bateau privé pour croisière événement',
    categoryId: 194,
  },

  // Personnels (8)
  {
    firstName: 'Saliu',
    lastName: 'Diallo',
    companyName: 'Serveurs Event Premium',
    activity: 'Service serveurs',
    phone: '+221771300053',
    email: 'saliu.diallo@serveurs.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Équipe serveurs formés et courtois',
    categoryId: 195,
  },
  {
    firstName: 'Oupa',
    lastName: 'Ba',
    companyName: 'Chef Pâtissier Privé',
    activity: 'Pâtissier professionnel',
    phone: '+221771300054',
    email: 'oupa.ba@patissier.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Chef pâtissier spécialisé mariage',
    categoryId: 195,
  },
  {
    firstName: 'Amadou',
    lastName: 'Gueye',
    companyName: 'Sommelier Conseil Événement',
    activity: 'Sommelier consultant',
    phone: '+221771300055',
    email: 'amadou.gueye@sommelier.sn',
    department: 'Dakar',
    commune: 'Plateau',
    shortDescription: 'Sommelier pour sélection vins',
    categoryId: 195,
  },
  {
    firstName: 'Fatimata',
    lastName: 'Sarr',
    companyName: 'Assistant Organisatrice',
    activity: 'Assistante organisatrice',
    phone: '+221771300056',
    email: 'fatimata.sarr@assistant.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Assistante jour J pour coordination',
    categoryId: 195,
  },
  {
    firstName: 'Youssouf',
    lastName: 'Ndiaye',
    companyName: 'Chef Cuisinier Moderne',
    activity: 'Chef cuisinier',
    phone: '+221771300057',
    email: 'youssouf.ndiaye@chef.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Chef spécialisé cuisine moderne',
    categoryId: 195,
  },
  {
    firstName: 'Mirèle',
    lastName: 'Diallo',
    companyName: 'Maître de Cérémonie Pro',
    activity: 'Maître de cérémonie',
    phone: '+221771300058',
    email: 'mirele.diallo@mc.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: "MC expérimenté tous types d'événements",
    categoryId: 195,
  },
  {
    firstName: 'Amandine',
    lastName: 'Ba',
    companyName: 'Staff Événement Complet',
    activity: 'Staff événement',
    phone: '+221771300059',
    email: 'amandine.ba@staff.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Équipe complète pour événement',
    categoryId: 195,
  },
  {
    firstName: 'Lambert',
    lastName: 'Gueye',
    companyName: 'Barista Café Events',
    activity: 'Barista professionnel',
    phone: '+221771300060',
    email: 'lambert.gueye@barista.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Barista pour station café événement',
    categoryId: 195,
  },

  // Pour Elle (8)
  {
    firstName: 'Mariam',
    lastName: 'Diallo',
    companyName: 'Salon Beauté Complète',
    activity: 'Salon de beauté',
    phone: '+221771300061',
    email: 'mariam.diallo@salon.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Coiffure, maquillage, spa complet',
    categoryId: 196,
  },
  {
    firstName: 'Hawa',
    lastName: 'Gueye',
    companyName: 'Couturière de Renom',
    activity: 'Couturière',
    phone: '+221771300062',
    email: 'hawa.gueye@couture.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Couturière spécialisée mariées',
    categoryId: 196,
  },
  {
    firstName: 'Aïssatou',
    lastName: 'Sow',
    companyName: 'Visagiste Maquillage Bridal',
    activity: 'Maquilleur professionnel',
    phone: '+221771300063',
    email: 'aissatou.sow@visagiste.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Maquillage spécialisé mariée',
    categoryId: 196,
  },
  {
    firstName: 'Aminata',
    lastName: 'Ndiaye',
    companyName: 'Coiffure Tresses & Chignon',
    activity: 'Coiffeuse spécialisée',
    phone: '+221771300064',
    email: 'aminata.ndiaye@coiffure.sn',
    department: 'Dakar',
    commune: 'Médina',
    shortDescription: 'Tresses, chignons et coiffures',
    categoryId: 196,
  },
  {
    firstName: 'Assiba',
    lastName: 'Ba',
    companyName: 'Mode Designer Africain',
    activity: 'Couturière designer',
    phone: '+221771300065',
    email: 'assiba.ba@designer.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Designer mode africaine moderne',
    categoryId: 196,
  },
  {
    firstName: 'Ndeye',
    lastName: 'Gueye',
    companyName: 'Accessoires Mode Prestige',
    activity: 'Accessoires de mode',
    phone: '+221771300066',
    email: 'ndeye.gueye@accessoires.sn',
    department: 'Dakar',
    commune: 'Plateau',
    shortDescription: 'Bijoux et accessoires haut de gamme',
    categoryId: 196,
  },
  {
    firstName: 'Khady',
    lastName: 'Diallo',
    companyName: 'Spa Mobile Wellness',
    activity: 'Services spa mobile',
    phone: '+221771300067',
    email: 'khady.diallo@spa.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Spa mobile pour bien-être',
    categoryId: 196,
  },
  {
    firstName: 'Fatoumata',
    lastName: 'Sall',
    companyName: 'Boutique Chaussures Luxe',
    activity: 'Chaussures de designer',
    phone: '+221771300068',
    email: 'fatoumata.sall@chaussures.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Chaussures de luxe et talons',
    categoryId: 196,
  },

  // Animation (12)
  {
    firstName: 'Seydou',
    lastName: 'Sow',
    companyName: 'Orchestre Jazz Dakar',
    activity: 'Groupe jazz',
    phone: '+221771300069',
    email: 'seydou.sow@jazz.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Groupe jazz professionnel',
    categoryId: 197,
  },
  {
    firstName: 'Aïda',
    lastName: 'Ba',
    companyName: 'Ballets Africains Prestige',
    activity: 'Danseurs professionnels',
    phone: '+221771300070',
    email: 'aida.ba@ballets.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Groupe danseurs danses africaines',
    categoryId: 197,
  },
  {
    firstName: 'Pape',
    lastName: 'Diallo',
    companyName: 'DJ Resident Remixeur',
    activity: 'DJ remixeur',
    phone: '+221771300071',
    email: 'pape.diallo@djresidence.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'DJ remixeur et producteur',
    categoryId: 197,
  },
  {
    firstName: 'Oumou',
    lastName: 'Gueye',
    companyName: 'Chanteuse Variété Prestige',
    activity: 'Chanteuse',
    phone: '+221771300072',
    email: 'oumou.gueye@chanteuse.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Chanteuse variété française et mbalax',
    categoryId: 197,
  },
  {
    firstName: 'Moussa',
    lastName: 'Sarr',
    companyName: 'Groupe Mbalax Sensation',
    activity: 'Groupe mbalax',
    phone: '+221771300073',
    email: 'moussa.sarr@mbalax.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Groupe mbalax traditionnel',
    categoryId: 197,
  },
  {
    firstName: 'Amandine',
    lastName: 'Ndiaye',
    companyName: 'Animations Jeux Enfants',
    activity: 'Animatrice jeux enfants',
    phone: '+221771300074',
    email: 'amandine.ndiaye@jeux.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Animations et jeux pour enfants',
    categoryId: 197,
  },
  {
    firstName: 'Cheikh',
    lastName: 'Ba',
    companyName: 'Magicien Illusionniste Pro',
    activity: 'Magicien illusionniste',
    phone: '+221771300075',
    email: 'cheikh.ba@magicien.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Magicien illusionniste pour événements',
    categoryId: 197,
  },
  {
    firstName: 'Marième',
    lastName: 'Diallo',
    companyName: 'Danseurs Salon Prestige',
    activity: 'Danseurs de salon',
    phone: '+221771300076',
    email: 'marieme.diallo@salonp.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Danseurs de salon professionnel',
    categoryId: 197,
  },
  {
    firstName: 'Youssouf',
    lastName: 'Gueye',
    companyName: 'Groupe Guitaristes Classiques',
    activity: 'Groupe guitare classique',
    phone: '+221771300077',
    email: 'youssouf.gueye@guitare.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Guitares classiques pour cérémonie',
    categoryId: 197,
  },
  {
    firstName: 'Talla',
    lastName: 'Ndiaye',
    companyName: 'Ventriloque & Marionnettes',
    activity: 'Ventriloque',
    phone: '+221771300078',
    email: 'talla.ndiaye@ventriloque.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Spectacles ventriloque enfants',
    categoryId: 197,
  },
  {
    firstName: 'Malick',
    lastName: 'Sall',
    companyName: 'Acrobates & Équilibristes',
    activity: 'Acrobate',
    phone: '+221771300079',
    email: 'malick.sall@acrobate.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Spectacles acrobatiques',
    categoryId: 197,
  },
  {
    firstName: 'Ndèye',
    lastName: 'Sarr',
    companyName: 'Clown Événement Drôle',
    activity: 'Clown professionnel',
    phone: '+221771300080',
    email: 'ndeye.sarr@clown.sn',
    department: 'Dakar',
    commune: 'Dakar',
    shortDescription: 'Clown pour animation enfants',
    categoryId: 197,
  },
];

async function main() {
  try {
    await AppDataSource.initialize();
    console.log('✅ Connexion à la base de données établie');

    // Étape 1: Créer les 80 prestataires supplémentaires
    console.log('\n📋 Ajout de 80 prestataires supplémentaires...');

    let createdCount = 0;
    const now = new Date();

    for (const providerData of PROVIDERS_DATA_ADDITIONAL) {
      const { categoryId, ...providerFields } = providerData;

      // Hasher le mot de passe
      const hashedPassword = await bcrypt.hash('Provider@123', 10);
      const providerId = randomUUID();

      // Insérer le prestataire via requête SQL
      await AppDataSource.query(
        `INSERT INTO providers (
          id, first_name, last_name, company_name, activity, 
          department, commune, phone, email,
          password, identity_doc_type, identity_doc_number,
          email_verified_at, phone_verified_at, is_active,
          show_phone_number, created_at, updated_at
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)`,
        [
          providerId,
          providerFields.firstName,
          providerFields.lastName,
          providerFields.companyName,
          providerFields.activity,
          providerFields.department,
          providerFields.commune,
          providerFields.phone,
          providerFields.email,
          hashedPassword,
          'passport',
          `SN${Math.random().toString(36).substring(2, 11)}`,
          now,
          now,
          true,
          false,
          now,
          now,
        ],
      );

      // Ajouter la catégorie du prestataire
      await AppDataSource.query(
        `INSERT INTO provider_categories (
          provider_id, category_id, sub_category_id, created_at
        ) VALUES ($1, $2, $3, $4)`,
        [providerId, categoryId, null, now],
      );

      createdCount++;
      if (createdCount % 10 === 0) {
        console.log(`  ✓ ${createdCount}/80 prestataires créés...`);
      }
    }

    console.log(
      `\n✅ ${createdCount} prestataires supplémentaires créés avec succès`,
    );

    // Étape 2: Vérification
    console.log('\n📋 Vérification des données...');
    const providersCount = await AppDataSource.query(
      'SELECT COUNT(*) FROM providers',
    );
    const categoriesStats = await AppDataSource.query(
      `SELECT 
        c.id, 
        c.name, 
        COUNT(pc.provider_id) as provider_count
      FROM categories c
      LEFT JOIN provider_categories pc ON c.id = pc.category_id
      WHERE c.id BETWEEN 161 AND 168
      GROUP BY c.id, c.name
      ORDER BY c.id`,
    );

    console.log(`\n  ✓ Total prestataires: ${providersCount[0].count}`);
    console.log('\n  Distribution par catégorie:');
    for (const stat of categoriesStats) {
      console.log(`    - ${stat.name}: ${stat.provider_count} prestataires`);
    }

    console.log('\n🎉 Ajout des 80 prestataires terminé avec succès!');
  } catch (error) {
    console.error('❌ Erreur:', error);
    process.exit(1);
  } finally {
    await AppDataSource.destroy();
  }
}

main();
